### ISSUE TITLE
How to change mod settings on a server?

### ISSUE THREAD

**Issue by dextraa9791** [SceptreOfficial/Enhanced-Movement-Rework#7]
Hi i succesfully added the base enhanced movement and your rework to my server. It's working fine, but i wanted to change some of the weight limits. When i try to do that from ingame, by going to game options > addons > enhanced movement, everything is greyed out. Is there a config file i can edit to change the weight limit for everyone?

**Comment by dextraa9791** [comment]
nvm, actually just found out you needed to login as admin

**Comment by SceptreOfficial** [comment]
Login as admin and go to the server tab to modify it/force clients, since it is a global setting. 
If you use a 'userconfig/cba_settings' configuration, you'll need to properly adjust that accordingly.

You can read the CBA settings documentation to learn more about the addon options menu. https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System#how-to-use-already-existing-settings

I'm marking this issue closed, but if this doesn't answer your question, let me know.
